package com.loyaltyone.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Transient;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

import io.swagger.annotations.ApiModelProperty;

@Entity
public class Submissions {
@Id
@GeneratedValue(strategy = GenerationType.SEQUENCE )
@Column(name = "postid")
@ApiModelProperty(notes = "The database generated product ID")
private long postid;
@ApiModelProperty(notes = "The post submitted by users")
private String post;
@ApiModelProperty(notes = "The name of users")
private String name;
@ApiModelProperty(notes = "The city of users")
private String city;
@ApiModelProperty(notes = "The latitude of city generated by googlegeocodeapi")
private String lat;
@ApiModelProperty(notes = "The longitude of city generated by googlegeocodeapi")
private String lng;
@Transient
@ApiModelProperty(notes = "The temperature generated by openweatherapi ")
private String temperature;
@ApiModelProperty(notes = "The response provided by user on post ")
private String response;
public String getName() {
	return name;
}
public void setName(String name) {
	this.name = name;
}
public String getCity() {
	return city;
}
public void setCity(String city) {
	this.city = city;
}
public String getResponse() {
	return response;
}
public void setResponse(String response) {
	this.response = response;
}
public String getPost() {
	return post;
}
public void setPost(String post) {
	this.post = post;
}

public long getPostid() {
	return postid;
}
public void setPostid(long postid) {
	this.postid = postid;
}

public String getLat() {
	return lat;
}
public void setLat(String lat) {
	this.lat = lat;
}
public String getLng() {
	return lng;
}
public void setLng(String lng) {
	this.lng = lng;
}

public String getTemperature() {
	return temperature;
}
public void setTemperature(String temperature) {
	this.temperature = temperature;
}
/**
 * 
 */
public Submissions() {
	
}

/**
 * @param post
 * @param name
 * @param city
 * @param string 
 */
public Submissions(long postid, String post, String name, String response) {
	super();
	this.postid = postid;
	this.post = post;
	this.name = name;
	this.response = response;
}
/**
 * @param post
 * @param name
 * @param city
 * @param lat
 * @param lng
 */
public Submissions(String post, String name, String city, String lat, String lng) {
	super();
	this.post = post;
	this.name = name;
	this.city = city;
	this.lat = lat;
	this.lng = lng;
}
/**
 * @param postid
 * @param response
 */
public Submissions(long postid, String response) {
	super();
	this.postid = postid;
	this.response = response;
}
/**
 * @param postid
 * @param post
 * @param name
 * @param city
 * @param response
 */
public Submissions(long postid, String post, String name, String city, String response) {
	super();
	this.postid = postid;
	this.post = post;
	this.name = name;
	this.city = city;
	this.response = response;
}
/**
 * @param postid
 * @param post
 * @param name
 * @param city
 * @param lat
 * @param lng
 * @param response
 */
public Submissions(long postid, String post, String name, String city, String lat, String lng, String response) {
	super();
	this.postid = postid;
	this.post = post;
	this.name = name;
	this.city = city;
	this.lat = lat;
	this.lng = lng;
	this.response = response;
}



}
